version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/Skillzcafe

permissions:
  - object: /var/www
    pattern: "*Skillzcafe*"
    owner: ubuntu
    group: ubuntu
    mode: 775
    type:
      - directory
  - object: /var/www/Skillzcafe
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 664
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/clean_folder.sh
      timeout: 60

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/restart_pm2.sh
      timeout: 60
