version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Skillzcafe
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/restart_pm2.sh
      timeout: 300
